### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by soemthlng** [RiS3-Lab/p2im#19]
I am using p2im in Ubuntu 16.05 LTS on VMWare.
The settings of VM are as below.
`Memory    14.9GB
Processors    4
Hard Disk    60GB`
I used PLC from `https://github.com/RiS3-Lab/p2im-real_firmware/tree/master/PLC` and run with this code `<repo_path>/model_instantiation/fuzz.py -c fuzz.cfg`

This error occurs.

    [-] Oops, the program crashed with one of the test cases provided. There are
    several possible explanations:

    - The test case causes known crashes under normal working conditions. If
      so, please remove it. The fuzzer should be seeded with interesting
      inputs - but not ones that cause an outright crash.

    - The current memory limit (2.00 GB) is too low for this program, causing
      it to die due to OOM when parsing valid files. To fix this, try
      bumping it up with the -m setting in the command line. If in doubt,
      try something along the lines of:

      ( ulimit -Sv $[2047 << 10]; /path/to/binary [...] <testcase )

      Tip: you can use http://jwilk.net/software/recidivm to quickly
      estimate the required amount of virtual memory for the binary. Also,
      if you are using ASAN, see docs/notes_for_asan.txt.

    - Least likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <lcamtuf@coredump.cx> for troubleshooting tips.

    [-] PROGRAM ABORT : Test case 'id:000000,orig:random' results in a crash
         Location : perform_dry_run(), afl-fuzz.c:2781

To solve this problem, I typed this command
`    root@ubuntu:/home/aiden/p2im/fuzzing/PLC/5# ulimit -Sv $[2047 << 10]; /home/aiden/p2im/fuzzing/PLC/5/PLC.elf`
Also this error occurs    
`    bash: /home/aiden/p2im/fuzzing/PLC/5/PLC.elf: cannot execute binary file: Exec format error`

Is there any way to make p2im recognize the 16 GB of memory allocated to the VM? or is there no other way to unlock the limit via ulimit -Sv? 
/etc/security/limits.conf has already been modified.

**Comment by luke-croak** [comment]
I had a similar issue. The cause wasn't the memory limit but my build/version of qemu. Running inside the docker container, produced by the below Dockerfile, solved the issue for me (since it was able to use the precompiled binary for qemu). The Dockerfile includes an example of setting up a run for the `Console` example firmware. All that's left to do is run `./exec.sh` inside the Docker container. I.e., after building the image, enter into the container `docker run -ti <CONTAINER>` and then run `./exec.sh`.

```
FROM ubuntu:16.04
RUN mkdir -p /home/project
WORKDIR /home/project

# Setting up necessary packages
RUN apt-get update && \
    apt-get install -y git build-essential gcc-arm-none-eabi zip python3 wget

# Setting up p2im
RUN git clone https://github.com/RiS3-Lab/p2im.git && \
    cd p2im/  && \
    git submodule update --init && \
    git submodule update --remote && \
    make -C afl/

# As an example, setting up the Console firmware
RUN WORKING_DIR=/home/project/p2im/fuzzing/Console/0 && \
    mkdir -p ${WORKING_DIR} && \
    cd ${WORKING_DIR} && \
    cp /home/project/p2im/externals/p2im-real_firmware/binary/Console .

WORKDIR /home/project/p2im/fuzzing/Console/0

RUN cp -r /home/project/p2im/fuzzing/templates/seeds inputs && \
    cp /home/project/p2im/fuzzing/templates/fuzz.cfg.template fuzz.cfg

# Setting up the seed so doesn't crash immediately
RUN echo "asdf" > inputs/random

# Manually setting up fuzz.cfg too for Console example
RUN sed -i '19s/.*/base        = \/home\/project\/p2im/' fuzz.cfg && \
    sed -i '21s/.*/program     = Console/' fuzz.cfg && \
    sed -i '23s/.*/run         = 0/' fuzz.cfg && \
    sed -i '47s/.*/board       = FRDM-K64F/' fuzz.cfg && \
    sed -i '48s/.*/mcu         = MK64FN1M0VLL12/' fuzz.cfg && \
    sed -i '61s/.*/img         = %(working_dir)s\/Console/' fuzz.cfg && \
    sed -i '68s/.*/objdump     = \/usr\/bin\/arm-none-eabi-objdump/' fuzz.cfg

# Creating simple executable script
RUN echo "#!/bin/bash" > exec.sh && \
    echo "/home/project/p2im/model_instantiation/fuzz.py -c fuzz.cfg" >> exec.sh && \
    chmod +x exec.sh
```

**Comment by zunlongzhou** [comment]
This problem occurred in several binary tests in the testcase of ubuntu1604 and ubuntu1804. Have you solved it?

**Comment by soemthlng** [comment]
@zunlongzhou  No, I can not solve this problem.
Same as luke-croak, I think it is not a memory limit problem.
I think this problem is caused by some binaries.

In my case, re-compiling some binaries worked.

**Comment by bofeng17** [comment]
It's most likely not a memory limit issue. I guess it's caused by "test cases crash", which causes QEMU crash or exit with a non-zero value (treated as a crash), you can figure out the "crash" reason by `./run_fw.py` following the instructions in https://github.com/RiS3-Lab/p2im#analyzing-crashinghanging-input

**Comment by jackniu1234** [comment]
I run ./run_fw.py mentioned by @bofeng17 and I figured out that the "crash" is caused by the symbol link in the precompiled qemu provided by the p2im corrupted!

I guess the reason is that I copied the git repository from windows to ubuntu virtual machine.

One solution I found is listed in 
https://askubuntu.com/questions/24266/error-while-loading-shared-libraries-file-too-short
