### ISSUE TITLE
 Can p2im only be used to test devices with source code?

### ISSUE THREAD

**Issue by Aaron911** [RiS3-Lab/p2im#7]

**Comment by bofeng17** [comment]
By design, P2IM does not need source code to model processor-peripheral interfaces. However, in our current prototype, firmware needs to be patched to invoke `startForkserver` aflcall before being fuzz-tested. You can find more details here https://github.com/RiS3-Lab/p2im/blob/master/docs/prep_fw_for_fuzzing.md
