### ISSUE TITLE
Dose p2im support the firmware that uses the SD card?

### ISSUE THREAD

**Issue by mintancy** [RiS3-Lab/p2im#8]
Hi, we tried to extend this work to support other boards and other firmware. The firmware we chose read files from the SD card. Now the fuzzing process did not work and we could not confirm the modification of the qemu source code to support other boards. Could you please let us know whether this work support SD card peripheral emulation or not? Thank you!

**Comment by bofeng17** [comment]
Thanks for your interest in P2IM. SD Card peripherals use the same process-peripheral interface (MMIO registers and interrupt) that P2IM models. P2IM are able to model those interfaces. However, we haven't  tested P2IM on SD card peripherals. So P2IM may not achieve the P2IE (processor-peripheral interface equivalence) property we defined in the paper, due to mis-categorized registers, or other unexpected reasons. Therefore, the firmware may not get the correct SD files from the SD card.
